"""Planning models, candidates, uncertainty categories, and investigation plans."""

from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional
from uuid import uuid4
from pydantic import BaseModel, Field

from cyberclaw.permissions.policy import ActionScope


def utc_now() -> datetime:
    return datetime.now(timezone.utc)


class UncertaintyType(str, Enum):
    """Categorization of investigative uncertainty."""

    UNKNOWN = "UNKNOWN"              # Attribute or entity is entirely absent
    AMBIGUOUS = "AMBIGUOUS"          # Multiple plausible interpretations exist
    UNCONFIRMED = "UNCONFIRMED"      # Inferred but lacks direct empirical observation
    CONTRADICTED = "CONTRADICTED"    # Conflicting evidence observations exist
    INCOMPLETE = "INCOMPLETE"        # Entity is partially profiled
    STALE = "STALE"                  # Historical information needs refreshed verification


class InformationValueDimension(str, Enum):
    """Dimension describing why seeking specific information is advantageous."""

    HYPOTHESIS_SUPPORT = "hypothesis_support"
    HYPOTHESIS_DISCONFIRMATION = "hypothesis_disconfirmation"
    CONTRADICTION_RESOLUTION = "contradiction_resolution"
    ENTITY_ENRICHMENT = "entity_enrichment"
    MISSING_EVIDENCE = "missing_evidence"
    CORROBORATION = "corroboration"


class StoppingCondition(str, Enum):
    """Explicit termination conditions for adaptive investigation planning."""

    OBJECTIVE_SATISFIED = "OBJECTIVE_SATISFIED"
    NO_ACTIONABLE_INFORMATION_GAPS = "NO_ACTIONABLE_INFORMATION_GAPS"
    NO_AUTHORIZED_CAPABILITIES = "NO_AUTHORIZED_CAPABILITIES"
    UNRESOLVED_CRITICAL_CONTRADICTION = "UNRESOLVED_CRITICAL_CONTRADICTION"
    REQUIREMENT_FAILURE_LIMIT = "REQUIREMENT_FAILURE_LIMIT"
    USER_REQUESTED_STOP = "USER_REQUESTED_STOP"
    PAUSED = "PAUSED"
    MAX_CYCLES_REACHED = "MAX_CYCLES_REACHED"


class PlanStatus(str, Enum):
    """Lifecycle state of an InvestigationPlan."""

    GENERATED = "GENERATED"
    VALIDATED = "VALIDATED"
    EXECUTED = "EXECUTED"
    REJECTED = "REJECTED"
    STOPPED = "STOPPED"


class CapabilityGap(BaseModel):
    """Structured representation of an unmet intelligence requirement where no capability exists.

    Serves as the bridge between investigative planning and Specialist self-development.
    """

    gap_id: str = Field(default_factory=lambda: str(uuid4()))
    investigation_id: str
    target_or_entity: str
    desired_evidence_type: str
    reason: str
    detected_at: datetime = Field(default_factory=utc_now)
    metadata: Dict[str, Any] = Field(default_factory=dict)


class RequirementCandidate(BaseModel):
    """Candidate proposal for an InformationRequirement generated by the Planner."""

    candidate_id: str = Field(default_factory=lambda: str(uuid4()))
    target_or_entity: str
    requested_evidence_types: List[str] = Field(default_factory=list)
    purpose: str
    value_dimension: InformationValueDimension = InformationValueDimension.MISSING_EVIDENCE
    uncertainty_type: UncertaintyType = UncertaintyType.UNKNOWN
    supporting_evidence_ids: List[str] = Field(default_factory=list)
    supporting_hypothesis_ids: List[str] = Field(default_factory=list)
    dependencies: List[str] = Field(default_factory=list)
    priority: int = Field(default=50, ge=1, le=100)
    required_capability: Optional[str] = None
    expected_information_value: str = ""
    permission_requirements: List[str] = Field(default_factory=list)
    risk_classification: ActionScope = ActionScope.REVERSIBLE
    created_at: datetime = Field(default_factory=utc_now)
    metadata: Dict[str, Any] = Field(default_factory=dict)

    def deduplication_key(self, investigation_id: str) -> str:
        """Deterministic deduplication key preventing redundant planning cycles."""
        types_key = ",".join(sorted(self.requested_evidence_types))
        return f"{investigation_id}:{self.target_or_entity}:{types_key}:{self.required_capability or ''}"


class InvestigationPlan(BaseModel):
    """A formal planning artifact representing proposed next information requirements."""

    plan_id: str = Field(default_factory=lambda: str(uuid4()))
    investigation_id: str
    current_investigation_state: str
    observed_evidence_references: List[str] = Field(default_factory=list)
    current_hypotheses: List[str] = Field(default_factory=list)
    unresolved_contradictions: List[str] = Field(default_factory=list)
    open_information_requirements: List[str] = Field(default_factory=list)
    candidate_next_requirements: List[RequirementCandidate] = Field(default_factory=list)
    capability_gaps: List[CapabilityGap] = Field(default_factory=list)
    reasoning_basis: str
    constraints: Dict[str, Any] = Field(default_factory=dict)
    generated_timestamp: datetime = Field(default_factory=utc_now)
    planner_version: str = "0.1.0"
    plan_status: PlanStatus = PlanStatus.GENERATED
    stopping_condition: Optional[StoppingCondition] = None

    @property
    def id(self) -> str:
        """Convenience alias for plan_id."""
        return self.plan_id
